name: flame_game
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^8.2.0
  dio: ^5.5.0+1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  flame: ^1.18.0
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4


flutter:
  uses-material-design: true
  generate: true
 
  assets:
    - assets/images/
    - assets/images/fruit/
    - assets/audio/